# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The lints are activated by the `flutter_lints` package, which contains the
# recommended set of lints for Flutter apps.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
